### ISSUE TITLE
compatibility with react-native-push-notification 

### ISSUE THREAD

**Issue by alexhochreiter** [skb1129/react-native-change-icon#82]
**Platform**
 - [ ] iOS
 - [X] Android

**Description**
Displaying local notifications with `react-native-push-notification` stopped working after switching the app-icon.
This is not really a bug within this library, but as it is caused by it i want to suggest adding a section to the readme, that states that it might be required for some other libraries to add additional classes to your java code like `android/app/src/main/java/at/mycompany/myappname/app/MainActivitythisisanactivityaliaswithamuchcoolericon.java`:
```java
package at.mycompany.myappname.app;
public class MainActivitythisisanactivityaliaswithamuchcoolericon extends MainActivity {}
```

**To Reproduce**
1. switch the app-icon, so any other activity than the default `.MainActivity` is running, receive a notification/try to display one with `PushNotification.localNotification` and boom, you ll receive the following error:
```
java.lang.ClassNotFoundException: at.mycompany.myappname.app.MainActivitythisisanactivityaliaswithamuchcoolericon
W  	at java.lang.Class.classForName(Native Method)
W  	at java.lang.Class.forName(Class.java:454)
W  	at java.lang.Class.forName(Class.java:379)
W  	at com.dieam.reactnativepushnotification.modules.RNPushNotificationHelper.getMainActivityClass(RNPushNotificationHelper.java:71)
W  	at com.dieam.reactnativepushnotification.modules.RNPushNotificationHelper.sendToNotificationCentreWithPicture(RNPushNotificationHelper.java:202)
W  	at com.dieam.reactnativepushnotification.modules.RNPushNotificationHelper$1.call(RNPushNotificationHelper.java:191)
W  	at com.dieam.reactnativepushnotification.modules.RNPushNotificationPicturesAggregator.finished(RNPushNotificationPicturesAggregator.java:169)
W  	at com.dieam.reactnativepushnotification.modules.RNPushNotificationPicturesAggregator.setBigPicture(RNPushNotificationPicturesAggregator.java:42)
W  	at com.dieam.reactnativepushnotification.modules.RNPushNotificationPicturesAggregator.setBigPictureUrl(RNPushNotificationPicturesAggregator.java:47)
W  	at com.dieam.reactnativepushnotification.modules.RNPushNotificationHelper.sendToNotificationCentre(RNPushNotificationHelper.java:197)
W  	at com.dieam.reactnativepushnotification.modules.RNPushNotification.presentLocalNotification(RNPushNotification.java:173)
W  	at java.lang.reflect.Method.invoke(Native Method)
W  	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
W  	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
W  	at com.facebook.jni.NativeRunnable.run(Native Method)
W  	at android.os.Handler.handleCallback(Handler.java:942)
W  	at android.os.Handler.dispatchMessage(Handler.java:99)
W  	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
W  	at android.os.Looper.loopOnce(Looper.java:226)
W  	at android.os.Looper.loop(Looper.java:313)
W  	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
W  	at java.lang.Thread.run(Thread.java:1012)
W  Caused by: java.lang.ClassNotFoundException: Didn't find class "at.mycompany.myappname.app.MainActivitythisisanactivityaliaswithamuchcoolericon" on path: DexPathList[[zip file "/data/app/~~aMMN4Khtk28iA5K61Tl_1w==/at.mycompany.myappname.app-LFKojQ5DJlS2dRAG-XAltw==/base.apk"],nativeLibraryDirectories=[/data/app/~~aMMN4Khtk28iA5K61Tl_1w==/at.mycompany.myappname.app-LFKojQ5DJlS2dRAG-XAltw==/lib/arm64, /data/app/~~aMMN4Khtk28iA5K61Tl_1w==/at.mycompany.myappname.app-LFKojQ5DJlS2dRAG-XAltw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
W  	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W  	... 22 more
E  No activity class found for the notification
```

**Expected behavior**
Not to interfere with other libraries to the point of breaking.

**Screenshots**
See quoted log above.

**Versions**
 - react-native: 0.70.6
 - react-native-change-icon: ^4.0.0

Again, this is mainly a suggestion, as this library applies some arcane Android magic only a few will be familiar with and hence mentioning this might potentially save some people days of debugging. I love your library anyways ❤️

**Comment by skb1129** [comment]
Thanks @alexhochreiter, will add this to the README
